### ISSUE TITLE
Discord RPC Showing is wrong if the game's language is not English

### ISSUE THREAD

**Issue by lucario387** [Its-Haze/league-rpc-linux#17]
I played on Japanese Server and with Japanese Language, and if I used league-rpc-linux, the champion's icon display is not working, as it's searching for an image of a champion with Japanese name and not English.

Reproduce steps:
- Change game client's language to Chinese, Japanese or Korean
- Get into a game, wait for the RPC to load image
- Click onto it in Discord
- See the image to not be the champion's, but just a blank png

**Comment by Its-Haze** [comment]
Hi. thanks for reporting this issue. I will try to reproduce it tomorrow and see if i can figure out a solution.

**Comment by Its-Haze** [comment]
Hi @lucario387 .

 I have now fixed the issue. please update to v1.0.1 and test it out..

https://github.com/Its-Haze/league-rpc-linux/releases/tag/v1.0.1

**Comment by lucario387** [comment]
```
Traceback (most recent call last):
  File "league_rpc_linux/__main__.py", line 6, in <module>
ModuleNotFoundError: No module named 'nest_asyncio'
[80597] Failed to execute script '__main__' due to unhandled exception!
```
I'll try to re-download league-rpc-linux then reply again

**Comment by Its-Haze** [comment]
You have to install the new dependencies in requirements.txt into your virtual environment if you are using one

**Comment by Its-Haze** [comment]
So just run pip install -r requirements.txt

Or install the executable from the releases page

**Comment by lucario387** [comment]
Very sorry for the late response. But now it works as intended. Tysm for the fix

**Comment by Its-Haze** [comment]
> Very sorry for the late response. But now it works as intended. Tysm for the fix

Glad to hear!!
